# Generated by Django 4.2.11 on 2026-07-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tech_stack', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('problem_solved', models.TextField(blank=True, null=True)),
                ('architecture', models.TextField(blank=True, null=True)),
                ('design_process', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('key_features', models.JSONField(blank=True, default=list, null=True)),
                ('target_users', models.JSONField(blank=True, default=list, null=True)),
                ('challenges', models.JSONField(blank=True, default=list, null=True)),
                ('results', models.JSONField(blank=True, default=list, null=True)),
                ('future_improvements', models.JSONField(blank=True, default=list, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, null=True)),
                ('faq', models.JSONField(blank=True, default=list, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.category')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
